name: 'Git Subtree Tree'
description: 'Trying out subtree commands'
author: 'Kevin Galligan'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

runs:
  using: node20
  main: dist/index.js
